const GET_ALL_GAMES = "GET_ALL_GAMES";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
const GET_VIDEOGAME_DETAIL = "GET_VIDEOGAME_DETAIL";
const GET_GENRES = "GET_GENRES";
const ORDER_BY = "ORDER_BY";
const FILTER_BY = "FILTER_BY";
const DELETE_GAME = "DELETE_GAME";

export {
  GET_ALL_GAMES,
  SEARCH_BY_NAME,
  GET_VIDEOGAME_DETAIL,
  GET_GENRES,
  ORDER_BY,
  FILTER_BY,
  DELETE_GAME,
};
